apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: citizen-report
data:
  NODE_ENV: "production"
  REPORT_SERVICE_PORT: "3002"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "citizen_report"
